# Generated by Django 5.1.4 on 2026-06-03 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('confirmed_fraud', 'Confirmed fraud'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('risk_score', models.PositiveSmallIntegerField()),
                ('ai_explanation', models.TextField(blank=True)),
                ('ai_explained_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_alerts', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='transactions.transaction')),
            ],
            options={
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=50)),
                ('rule_label', models.CharField(max_length=120)),
                ('weight', models.PositiveSmallIntegerField()),
                ('detail', models.CharField(max_length=255)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_hits', to='fraud.alert')),
            ],
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='fraud_alert_status_f7b854_idx'),
        ),
    ]
